server:
  port: 8761


spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
  server:
    wait-time-in-ms-when-sync-empty: 0