apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-app
  labels:
    app: identity-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : identity-service-app
  template:
    metadata:
      labels:
        app: identity-service-app
    spec:
      containers:
      - name: identity-service-app
        image: reshangayantha/identity-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8081

---

kind: Service
apiVersion: v1
metadata:
  name:  identity-service-svc
spec:
  selector:
    app:  identity-service-app
  ports:
  - port:  80
    targetPort:  8081