server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: identity-service
          uri: lb:http://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**


        - id: organization-service-organization
          uri: lb:http://ORGANIZATION-SERVICE
          predicates:
            - Path=/api/v1/organization/**
          filters:
            - AuthenticationFilter

        - id: organization-service-mentor
          uri: lb:http://ORGANIZATION-SERVICE
          predicates:
             - Path=/api/v1/mentor/**
          filters:
             - AuthenticationFilter


        - id: admin-service
          uri: lb:http://ADMIN-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - AuthenticationFilter


        - id: student-service
          uri: lb:http://STUDENT-SERVICE
          predicates:
            - Path=/api/v1/student/**
          filters:
            - AuthenticationFilter


        - id: project-service
          uri: lb:http://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/project/**
          filters:
            - AuthenticationFilter